@baseUrl = http://103.159.132.89:8081

# 1. Start by registering Individual/Resident to get a registerId
 POST {{baseUrl}}/registers/resident
Content-Type: application/json

{
    "nricNumber": "881223145678",
    "tinNumber": "MA2819827D",
    "residentName": "Tan Kah Kow",
    "contactNumber": "0123456789",
    "contactEmail": "tkk@maxpark.com",
    "residentAddressLine1": "10 Anson Road",
    "residentAddressLine2": "",
    "residentPlate":  {
        "plateNumber": "WSS8674",
        "vehicleType": "1",
        "vehiclePath": "uploads/35c7b59f-046c-4622-8025-56cdb6fe10f5/plates/WSS9899_vehicle_file.jpg"
    },
    "residentSupportingFiles": {
        "spaPath": "uploads/35c7b59f-046c-4622-8025-56cdb6fe10f5/plates/WSS9899_spa_file.jpg",
        "electricBillPath": "uploads/35c7b59f-046c-4622-8025-56cdb6fe10f5/plates/WSS9899_electricity_file.jpg"
    }
}

###
# 2. Presigned URL for individual/resident file upload using registerId from previous step
GET {{baseUrl}}/presigned?registerId=35c7b59f-046c-4622-8025-56cdb6fe10f5&fileType=plate&fileName=M2U_20251203_1412.pdf&plateNumber=WSS9899


###
# 3. Finalize Individual/Resident registration
POST {{baseUrl}}/registers/resident/finalize
Content-Type: application/json

{
    "nricNumber": "881223145678",
    "tinNumber": "MA2819827D",
    "residentName": "Tan Kah Kow",
    "contactNumber": "012345678",
    "contactEmail": "tkk@maxpark.com",
    "residentAddressLine1": "10 Anson Road",
    "residentAddressLine2": "",
    "residentPlate":  {
        "plateNumber": "WSS9899",
        "vehicleType": "1",
        "vehiclePath": "uploads/35c7b59f-046c-4622-8025-56cdb6fe10f5/plates/WSS9899_vehicle_file.jpg"
    },
    "residentSupportingFiles": {
        "spaPath": "uploads/35c7b59f-046c-4622-8025-56cdb6fe10f5/plates/WSS9899_spa_file.jpg",
        "electricBillPath": "uploads/35c7b59f-046c-4622-8025-56cdb6fe10f5/plates/WSS9899_electricity_file.jpg"
    }
}

####
# 1. Start by registrating Company to get a registerId
POST {{baseUrl}}/registers/company
Content-Type: application/json

{
    "companyRegistrationNumber": "SM0000001A",
    "tinNumber": "MA2819827D",
    "companyName": "MaxPark Pte Ltd",
    "contactPerson": "Tan Kah Kow",
    "contactNumber": "012345678",  
    "contactEmail": "tkk@maxpark.com",
    "companyAddressLine1": "10 Anson Road",
    "companyAddressLine2": "",
    "companyPlates": [
        {
            "nricNumber": "881223145678",
            "plateNumber": "WSS8674",
            "vehicleType": "1",
            "spaPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_spa_file.jpg",
            "electricBillPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_electricity_file.jpg",
            "vehiclePath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_vehicle_file.jpg"
        },
        {
            "nricNumber": "881223145678",
            "plateNumber": "BBB222",
            "vehicleType": "1",
            "spaPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_spa_file.jpg",
            "electricBillPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_electricity_file.jpg",
            "vehiclePath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_vehicle_file.jpg"
        }
    ]
}

###
# 2. Presigned URL for company file upload using registerId from previous step
GET {{baseUrl}}/presigned?registerId=95fc22cc-ecb0-44a6-8246-4dbfed453e88&fileType=general&fileName=M2U_20251203_1412.pdf&employerId=E000000227&contentType=application%2Fpdf

### Upload PDF using presigned URL
PUT https://maxpark-opp-registration.oss-ap-southeast-3.aliyuncs.com/E000000227_M2U_20251203_1412.pdf?Expires=1767713149\u0026OSSAccessKeyId=LTAI5tJmXxFAiCr31QRFCTo6\u0026Signature=u%2F%2B0QMpOv1pUcVYvXCl0mMh3c2I%3D

< C:/Users/kahwo/Downloads/M2U_20251203_1412.pdf

###
# 3. Finalize Company registration
POST {{baseUrl}}/registers/company/finalize
Content-Type: application/json

{
    "employerID": "E000000221",
    "companyRegistrationNumber": "SM0000001A",
    "tinNumber": "MA2819827D",
    "companyName": "MaxPark Pte Ltd",
    "contactPerson": "Tan Kah Kow",
    "contactNumber": "012345678",  
    "contactEmail": "tkk@maxpark.com",
    "companyAddressLine1": "10 Anson Road",
    "companyAddressLine2": "",
    "companyPlates": [
        {
            "nricNumber": "881223145678",
            "plateNumber": "WSS9899",
            "vehicleType": "1",
            "spaPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_spa_file.jpg",
            "electricBillPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_electricity_file.jpg",
            "vehiclePath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/plates/WSS9899_vehicle_file.jpg"
        }
    ],
    "companySupportingFiles": {
        "ssmPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/general/E000000221_smm_file.jpg",
        "electricBillPath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/general/E000000221_electricity_file.jpg",
        "vehiclePath": "uploads/95fc22cc-ecb0-44a6-8246-4dbfed453e88/general/E000000221_vehicle_file.jpg"
    }
}